name: Get Unity License

on:
  workflow_dispatch:

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request Unity license file
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.3.5f1

      - name: Upload license request file
        uses: actions/upload-artifact@v4
        with:
          name: unity-license-request
          path: ./*.alf